# Generated by Django 4.1 on 2022-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mymodel',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 1)), name='Age should not be less than one'),
        ),
    ]
